# Generated by Django 4.1.5 on 2023-01-26 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250, verbose_name='Заголовк')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('content', models.CharField(max_length=250, verbose_name='Содержимое')),
                ('image', models.CharField(max_length=100, verbose_name='Изображение')),
                ('create_date', models.DateField(default=datetime.datetime(2023, 1, 26, 19, 11, 57, 694469, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('True', 'положительный'), ('False', 'отрицательный')], default='False', max_length=15)),
                ('view', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description_1', models.CharField(max_length=100, verbose_name='Описание 1')),
                ('description_2', models.CharField(max_length=100, verbose_name='Описание 2')),
                ('description_3', models.CharField(max_length=100, verbose_name='Описание 3')),
                ('description_4', models.CharField(max_length=100, verbose_name='Описание 4')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
