# Generated by Django 4.1.5 on 2023-01-26 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbl', '0002_alter_blog_create_date_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 26, 19, 18, 9, 829092, tzinfo=datetime.timezone.utc)),
        ),
    ]
