# Generated by Django 4.1.5 on 2023-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbl', '0009_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
